### ISSUE TITLE
Update the dependency on urllib3 to >2.0?

### ISSUE THREAD

**Issue by johanneskastl** [elastic/elastic-transport-python#102]
Could the dependency for urllib3 be updated to work with urllib 2.x?
This is one of the modules in my dependency chain, and it seems to be the only one still requiring urllib <2.

Unfortunately, I am not a python guy, so I cannot be of help with the actual implementation...

**Comment by aqeelat** [comment]
@pquentin @sethmlarson is this something that will be worked on? 👀
I can probably help out here if outside contributors are welcome.

**Comment by sethmlarson** [comment]
@aqeelat If you could contribute a PR fixing this issue that would be great!

**Comment by jgb** [comment]
Any news on this one? There was a patch in #105 but that PR got closed without merging.

**Comment by jessicawrr** [comment]
Ask the same. We are blocked by this issue.

**Comment by pquentin** [comment]
Working on it in https://github.com/elastic/elastic-transport-python/pull/121 - I need to test it more.

**Comment by pquentin** [comment]
[8.10.0](https://pypi.org/project/elastic-transport/8.10.0/) supports urllb3 1.26.x and 2.x. This makes me happy as an elastic-transport-python *and* urllib3 maintainer. :) Closing, thanks for your patience!
