### ISSUE TITLE
sdist is missing tests

### ISSUE THREAD

**Issue by mtelka** [elastic/elastic-transport-python#119]
The sdist package at PyPI is missing tests.  Please add tests to sdist to make downstream testing easier.  Thank you.

**Comment by pquentin** [comment]
Hello! The Python community appears to be divided over this and there's no current recommendation to include tests or docs (see https://discuss.python.org/t/should-sdists-include-docs-and-tests/14578/115) so I won't be working on this, sorry. That said, I would accept a pull request that implements this.
