### ISSUE TITLE
8.11.0:  Tests in sdist are incomplete

### ISSUE THREAD

**Issue by mtelka** [elastic/elastic-transport-python#134]
The `tests` directory in the 8.11.0 sdist is missing many files.  There are only `tests/test_*` files included and everything else is missing so testing fails:
```
Traceback:
/usr/lib/python3.9/vendor-packages/_pytest/python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
/usr/lib/python3.9/vendor-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:986: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:680: in _load_unlocked
    ???
/usr/lib/python3.9/vendor-packages/_pytest/assertion/rewrite.py:186: in exec_module
    exec(co, module.__dict__)
tests/test_transport.py:41: in <module>
    from tests.conftest import DummyNode
E   ModuleNotFoundError: No module named 'tests.conftest'
```
PS: I assume it is supposed that tests should be included in sdist because of #132.

**Comment by pquentin** [comment]
Right, good point. I tested locally, and `conftest.py` is indeed the only missing part. We could also include `noxfile.py` to make it easier to run tests too. And make sure those two files are not in the wheel.

As a second step we could also use the sdist to run tests, but I'm not sure how easy it is while keeping the ease of use of nox.

cc @parona-source
