### ISSUE TITLE
Expose TransportApiResponse

### ISSUE THREAD

**Issue by pquentin** [elastic/elastic-transport-python#145]
The [documented way to call `perform_request` on a node](https://elastic-transport-python.readthedocs.io/en/latest/nodes.html#elastic_transport.Urllib3HttpNode.perform_request) is to expect a tuple in response, `Tuple[ApiResponseMeta, bytes]`. But the actual underlying type is `TransportApiResponse`:

```
class TransportApiResponse(NamedTuple):
    meta: ApiResponseMeta
    body: Any
```

As pointed out by @ywangd, It would make sense to [expose it alongside other responses types](https://github.com/elastic/elastic-transport-python/blob/d85d0cfb435606dbf68a3c6b292f7fc5e6956dba/elastic_transport/__init__.py#L43-L48) and change the Nodes docs page to use it.

**Comment by JessicaGarson** [comment]
Opened a [PR here](https://github.com/elastic/elastic-transport-python/pull/160). I have some linting issues it seems. Should I be using Black for formatting?

**Comment by JessicaGarson** [comment]
I figured out the formatting issues!
