### ISSUE TITLE
Certificate chain APIs may change in Python 3.13

### ISSUE THREAD

**Issue by sethmlarson** [elastic/elastic-transport-python#162]
Didn't test this directly, but I'm aware that the certificate chain APIs may change in 3.13. Might be a good idea to test to make sure [the current usage](https://github.com/elastic/elastic-transport-python/blob/main/elastic_transport/_node/_urllib3_chain_certs.py#L113) doesn't break.

**Comment by pquentin** [comment]
Thank you for the heads-up! :green_heart:
