### ISSUE TITLE
Support for async HTTPX

### ISSUE THREAD

**Issue by b4sus** [elastic/elastic-transport-python#95]
Hello,

In our project we are already using HTTPX for async http calls. We are also using elasticsearch-py. As I wanted to avoid adding another dependency (aiohttp), I implemented (rather simple) custom node using HTTPX.
Is there a plan to support it directly here in transport? Or would you be open for such contribution?

Thanks,
b4sus

**Comment by pquentin** [comment]
Hello, and sorry for the late reply! I would gladly accept such a contribution. It would make Trio support much easier too.

**Comment by mmahacek** [comment]
Is this issue still open, or did PR #137 resolve this?

**Comment by pquentin** [comment]
Good call. This was resolved and released [as part of 8.13.0](https://github.com/elastic/elastic-transport-python/releases/tag/v8.13.0). Thanks!
